config/routes.rb
Rails.application.routes.draw do
  resources :groups

  resources :people

root 'groups#index'
 get 'randommmm' => 'groups#random', as: :dunno

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :people 
	
end

app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :group
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
# ici le code pr le random ------
def random
@people = Person.all
@groups = Group.all
alone_id=Person.all.to_a.map {|x| x.id}
#
if Group.all.count > 2
  #
    while alone_id.count > 0
      #
        Group.all.each do |gp|
          #
          a =alone_id.sample
          #
          alone_id.delete(a)
          #
          Person.find(a).update_attributes(group_id:  gp.id)   unless alone_id.count == 0
          #
        end
      end
    end
redirect_to root_path notice:"Groups have been randomize"

end

#------
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @people = Person.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @people = Person.all
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group créee avec succés.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :salle, :tache)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @people = Person.all
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :tel, :group_id, :sensei)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :salle %><br>
    <%= f.text_field :salle %>
  </div>
  <div class="field">
    <%= f.label :tache %><br>
    <%= f.text_field :tache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">

  <%= link_to "Group", groups_path,  :class => "btnhome" %>
   <%= link_to "Editions des utilisateurs", people_path,  :class => "btnuser" %>

<h1>Listing Groups</h1>

 <table class="table">
 <thead>
   <tr>
     <th>Name</th>
     <th>Salle</th>
     <th>Tache</th>
     <th>Membres</th>
     <th colspan="2"></th>
   </tr>
 </thead>

 <tbody>
   <% @groups.each do |group| %>
   <tr>
     <td><%= group.name %></td>
     <td><%= group.salle %></td>
     <td><%= group.tache %></td>
     <td></td>
     <td><%= link_to 'Show', group, :class => "btnshow" %></td>
     <td><%= link_to '+', edit_group_path(group), :class => "btnedit" %></td>
    
   </tr>
   <% group.people.each do |person| %>
   <tr>
     <td></td>
     <td></td>
     <td></td>
     <td><%= person.name %>
     <%= person.sensei? ? " - Sensei" : "" %></td>
     <td><%= best_in_place person, :group_id , :as => :select, :collection => {"nil" => "Sans groupe"}%></td>
     <td></td>
     <td></td>
   </tr>
     <% end %>
     <% end %>
   </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path, {:class => "btnedition"} %>
<%= link_to 'Random', dunno_path, {:class => "btnedition"} %> <!-- ici le btn random pr -->
</div>




<!--//////////////////////   ici la liste people /////////////////////////////// -->

<div class="container">

<h1>Listing People</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
     <th>Email</th>
      <th>Tel</th>
      <th>Group</th>
      <th>Sensei</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
    
        <% if person.group_id == "nil" || person.group_id == 0 %>
        <td><%= best_in_place person, :name %></td> <!-- ici la synthaxe de best in place pr le name -->
        
        <td><%= person.email %></td>
        <td><%= person.tel %></td>
        <td><%= person.group_id %></td>
        <td><%= best_in_place person, :sensei, :as => :select, :collection => {"1" => "Sensei", "2" => "visiteur"} %><%= person.sensei? ? " - Sensei" : "" %></td>
        <!-- ici la synthaxe pr choisir le sensei -->

        <td><%= link_to 'Show', person, :class => "btnshow" %></td>
        <td><%= link_to '+', edit_person_path(person), :class => "btnedit" %></td>
      </tr>
        <%end%><!-- ici le end pr la boucle qui affiche les user dans les groupe et les efface de la liste-->

    <% end %>
  </tbody>
</table>

<br>

</div>
</div>
<%= link_to 'New Person', new_person_path%>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<h1>Listing <%= @group.name %></h1>
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Salle:</strong>
  <%= @group.salle %>
</p>

<p>
  <strong>Tache:</strong>
  <%= @group.tache %>
</p>

<p>
<strong>Members:</strong>
<p>
<% @group.people.each do |person| %>
<%= person.sensei? ? "- sensei" : "" %>
<p>
<%= person.name %>
   <% end %>
  </p>

<%= link_to 'Edit', edit_group_path(@group), :class => "btnedition" %> |
<%= link_to 'Back', groups_path, :class => "btnback" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projetgroups</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
   <%= f.label :group_id %><br>
   <%= f.select :group_id, options_for_select(Group.all.to_a.map {|x| [ x.name, x.id]}) %>
 </div>
  
  <div class="field">
    <%= f.label :sensei %><br>
    <%= f.check_box :sensei %> <!-- ici check box car boolean pr le sensei true ou false si coche -->
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<h1>Listing People</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th>Group</th>
      <th>Sensei</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.tel %></td>
        <td><%= person.group_id %></td>
        <td><%= person.sensei %></td>
        <td><%= link_to 'Show', person, {:class => "btnedition"} %></td>
        <td><%= link_to 'Edit', edit_person_path(person), {:class => "btnedit"} %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @person.tel %>
</p>

<p>
  <strong>Sensei:</strong>
  <%= @person.sensei %>
</p>


 

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>